# Generated by Django 5.0.6 on 2025-01-11 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('salary', models.CharField(blank=True, max_length=200)),
                ('experience', models.CharField(blank=True, max_length=300)),
                ('education', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('job_type', models.CharField(blank=True, max_length=500)),
                ('work_mode', models.CharField(blank=True, max_length=500)),
                ('required_skills', models.CharField(max_length=900)),
                ('roles_and_responsibilities', models.CharField(blank=True, max_length=1500)),
                ('jon_link', models.CharField(blank=True, max_length=400)),
                ('company_name', models.CharField(blank=True, max_length=300)),
                ('added_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
