# Generated by Django 5.0.6 on 2025-01-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_jobs', '0002_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='jon_link',
            new_name='job_link',
        ),
    ]
