# Generated by Django 5.0.6 on 2025-01-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_jobs', '0003_rename_jon_link_jobs_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='newuser',
            name='phone_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
