# Generated by Django 5.0.6 on 2025-02-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_jobs', '0004_newuser_fullname_newuser_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
