# Generated by Django 5.0.6 on 2025-02-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_jobs', '0005_jobs_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_link',
            field=models.CharField(default='nolink', max_length=400),
        ),
    ]
