# Generated by Django 5.0.6 on 2025-02-09 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_jobs', '0007_jobs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 2, 9)),
            preserve_default=False,
        ),
    ]
