# Generated by Django 5.0.6 on 2025-02-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_jobs', '0008_jobs_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='newuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
