# Generated by Django 5.0.6 on 2025-02-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_jobs', '0010_appliedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='company',
            field=models.IntegerField(),
        ),
    ]
