# Generated by Django 5.0.6 on 2025-02-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_jobs', '0013_jobs_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('phone_no', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
