# Generated by Django 5.0.6 on 2025-02-22 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_jobs', '0013_jobs_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(default='qualification', max_length=100)),
                ('year_of_exp', models.CharField(default='exp', max_length=250)),
                ('area_of_interest', models.CharField(default='interest', max_length=250)),
                ('year_of_passing', models.CharField(default='year', max_length=100)),
                ('user_resume', models.FileField(blank=True, null=True, upload_to='user_resumes/')),
                ('skills', models.CharField(default='skills', max_length=700)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
