# Generated by Django 5.0.6 on 2025-02-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_jobs', '0014_contact_us'),
        ('external_jobs', '0014_userdetails'),
    ]

    operations = [
    ]
