# Generated by Django 5.0.6 on 2025-03-01 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_jobs', '0015_merge_0014_contact_us_0014_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_jobs.jobs'),
        ),
    ]
