# Generated by Django 5.0.6 on 2025-04-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_jobs', '0017_alter_userdetails_area_of_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='area_of_interest',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='skills',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='year_of_exp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='year_of_passing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
